export const posts = [
  {
    title: "Oferta del día",
    caption: "30% de descuento en televisores Samsung 4K",
    image_gallery: ["https://picsum.photos/1280/720?random=1"],
    post_platform: "facebook",
    date: "2023-10-25",
    status: "published",
    visibility: true,
    post_type: "post",
  },
  {
    title: "Prenda de la semana",
    caption: "Nuevos vestidos de verano con 50% de descuento",
    image_gallery: [
      "https://picsum.photos/1280/720?random=2",
      "https://picsum.photos/1280/720?random=3",
    ],
    post_platform: "instagram",
    date: "2023-10-26",
    status: "pending",
    visibility: false,
    post_type: "reel",
  },
  {
    title: "Lanzamiento de producto",
    caption: "Nuevo smartphone Xiaomi Redmi 10X al mejor precio",
    image_gallery: [
      "https://picsum.photos/1280/720?random=3",
      "https://picsum.photos/1280/720?random=4",
    ],
    post_platform: "tiktok",
    date: "2023-10-27",
    status: "draft",
    visibility: false,
    post_type: "post",
  },
  {
    title: "Rebajas de Octubre",
    caption: "Descuentos en todas las secciones",
    image_gallery: ["https://picsum.photos/1280/720?random=5"],
    post_platform: "youtube",
    date: "2023-10-28",
    status: "approved",
    visibility: true,
    post_type: "reel",
  },
  {
    title: "Nueva colección",
    caption: "Llegó la nueva colección Otoño/Invierno con los últimos looks",
    image_gallery: ["https://picsum.photos/1280/720?random=6"],
    post_platform: "linkedin",
    date: "2023-10-29",
    status: "customer_changes",
    visibility: true,
    post_type: "post",
  },
  {
    title: "Producto destacado",
    caption: "Auriculares inalámbricos Apple AirPods Pro al 20% de descuento",
    image_gallery: ["https://picsum.photos/1280/720?random=7"],
    post_platform: "pinterest",
    date: "2023-10-30",
    status: "pending",
    visibility: false,
    post_type: "reel",
  },
  {
    title: "¡No te lo pierdas!",
    caption: "Últimas unidades del Smart TV Samsung 75» al precio más bajo",
    image_gallery: ["https://picsum.photos/1280/720?random=8"],
    post_platform: "x_twitter",
    date: "2023-10-31",
    status: "published",
    visibility: true,
    post_type: "post",
  },
  {
    title: "Lo más vendido",
    caption: "El celular Motorola G50 cae a su mínimo histórico",
    image_gallery: ["https://picsum.photos/1280/720?random=9"],
    post_platform: "facebook",
    date: "2023-10-17",
    status: "draft",
    visibility: false,
    post_type: "reel",
  },
  {
    title: "Para tu cocina",
    caption: "Ollas, sartenes y accesorios de cocina con grandes ofertas",
    image_gallery: ["https://picsum.photos/1280/720?random=10"],
    post_platform: "instagram",
    date: "2023-10-16",
    status: "customer_changes",
    visibility: false,
    post_type: "post",
  },
  {
    title: "Imperdible",
    caption: "Jamón serrano con 30% de descuento esta semana",
    image_gallery: ["https://picsum.photos/1280/720?random=12"],
    post_platform: "tiktok",
    date: "2023-10-15",
    status: "customer_changes",
    visibility: true,
    post_type: "reel",
  },
  {
    title: "Inicio de mes",
    caption: "Aprovecha las mejores ofertas en productos seleccionados",
    image_gallery: ["https://picsum.photos/1280/720?random=13"],
    post_platform: "youtube",
    date: "2023-10-01",
    status: "published",
    visibility: true,
    post_type: "post",
  },
  {
    title: "Llegó la primavera",
    caption: "Renueva tu clóset con nuestra nueva colección",
    image_gallery: ["https://picsum.photos/1280/720?random=14"],
    post_platform: "linkedin",
    date: "2023-10-01",
    status: "pending",
    visibility: false,
    post_type: "reel",
  },
  {
    title: "Para tu mascota",
    caption: "Alimentos y accesorios para perros y gatos en promoción",
    image_gallery: ["https://picsum.photos/1280/720?random=15"],
    post_platform: "pinterest",
    date: "2023-10-03",
    status: "draft",
    visibility: false,
    post_type: "post",
  },
  {
    title: "¡Para los más pequeños!",
    caption: "Juguetes y ropa de bebé con grandes descuentos",
    image_gallery: ["https://picsum.photos/1280/720?random=16"],
    post_platform: "x_twitter",
    date: "2023-10-04",
    status: "approved",
    visibility: true,
    post_type: "reel",
  },
  {
    title: "De vuelta al cole",
    caption: "Mochilas, útiles y más con precios escolares",
    image_gallery: ["https://picsum.photos/1280/720?random=17"],
    post_platform: "Facebook",
    date: "2023-10-05",
    status: "approved",
    visibility: true,
    post_type: "post",
  },
  {
    title: "Para tu hogar",
    caption: "Muebles, electrodomésticos y artículos de decoración en oferta",
    image_gallery: ["https://picsum.photos/1280/720?random=18"],
    post_platform: "instagram",
    date: "2023-10-05",
    status: "pending",
    visibility: false,
    post_type: "reel",
  },
  {
    title: "Cuida tu salud",
    caption: "Suplementos vitamínicos naturales con 20% de descuento",
    image_gallery: ["https://picsum.photos/1280/720?random=19"],
    post_platform: "tiktok",
    date: "2023-10-07",
    status: "published",
    visibility: true,
    post_type: "post",
  },
  {
    title: "Para tu auto",
    caption: "Llantas, baterías y accesorios para tu vehículo en oferta",
    image_gallery: ["https://picsum.photos/1280/720?random=20"],
    post_platform: "linkedin",
    date: "2023-10-08",
    status: "draft",
    visibility: false,
    post_type: "reel",
  },
  {
    title: "Temporada de ofertas",
    caption: "Aprovecha los precios bajos en todos nuestros productos",
    image_gallery: ["https://picsum.photos/1280/720?random=21"],
    post_platform: "pinterest",
    date: "2023-10-09",
    status: "pending",
    visibility: false,
    post_type: "post",
  },
  {
    title: "Para tu comodidad",
    caption: "Sábanas, toallas y artículos para el baño en promoción",
    image_gallery: ["https://picsum.photos/1280/720?random=22"],
    post_platform: "x_twitter",
    date: "2023-10-10",
    status: "published",
    visibility: true,
    post_type: "reel",
  },
];

export const postStatuses = [
  {
    className: "flex items-center",
    color: "bg-sky-500",
    text: "Published",
  },
  {
    className: "flex items-center",
    color: "bg-red-500",
    text: "Customer changes",
  },
  {
    className: "flex items-center",
    color: "bg-green-500",
    text: "Approved",
  },
  {
    className: "flex items-center",
    color: "bg-yellow-500",
    text: "Pending",
  },
  {
    className: "flex items-center",
    color: "bg-purple-500",
    text: "Draft",
  },
];

export const companies = [
  {
    id: 1,
    name: "Company A",
    email: "contact@companyA.com",
    phone_number: "+1 (123) 456-7890",
    address: "123 Main Street",
    country: "USA",
  },
  {
    id: 2,
    name: "Company B",
    email: "info@companyB.com",
    phone_number: "+44 (20) 1234 5678",
    address: "456 Elm Avenue",
    country: "UK",
  },
  {
    id: 3,
    name: "Company C",
    email: "support@companyC.com",
    phone_number: "+33 (1) 2345 6789",
    address: "789 Oak Lane",
    country: "France",
  },
  {
    id: 4,
    name: "Company D",
    email: "sales@companyD.com",
    phone_number: "+49 (30) 1234 5678",
    address: "567 Birch Road",
    country: "Germany",
  },
  {
    id: 5,
    name: "Company E",
    email: "info@companyE.com",
    phone_number: "+81 (3) 1234 5678",
    address: "101 Pine Street",
    country: "Japan",
  },
  {
    id: 6,
    name: "Company F",
    email: "contact@companyF.com",
    phone_number: "+39 (06) 1234 5678",
    address: "202 Cedar Avenue",
    country: "Italy",
  },
  {
    id: 7,
    name: "Company G",
    email: "support@companyG.com",
    phone_number: "+34 (91) 123 4567",
    address: "303 Maple Lane",
    country: "Spain",
  },
  {
    id: 8,
    name: "Company H",
    email: "sales@companyH.com",
    phone_number: "+61 (2) 1234 5678",
    address: "404 Walnut Road",
    country: "Australia",
  },
  {
    id: 9,
    name: "Company I",
    email: "info@companyI.com",
    phone_number: "+65 1234 5678",
    address: "505 Willow Avenue",
    country: "Singapore",
  },
  {
    id: 10,
    name: "Company J",
    email: "contact@companyJ.com",
    phone_number: "+86 10 1234 5678",
    address: "606 Redwood Lane",
    country: "China",
  },
];
